### ISSUE TITLE
Server unescapes bad resource key in returned JSON

### ISSUE THREAD

**Issue by stuartlangridge** [51Degrees/pipeline-python#1]
```bash
$ curl https://cloud.51degrees.com/api/v4/accessibleProperties?resource=ABC%0A
{ "status":"400", "errors": ["ABC
 not a valid resource key"] }
```

Obviously the key `ABC\n` is not valid. However, the returned JSON has the value of that control character (a newline) unescaped in it, which makes that returned JSON invalid. This should be fixed on the server.

This also fails in `cloudrequestengine.py` (specifically https://github.com/51Degrees/pipeline-python/blob/2b4fd7a3758e20eec3ec5a42449e7e47beedc826/fiftyone_pipeline_cloudrequestengine/fiftyone_pipeline_cloudrequestengine/cloudrequestengine.py#L166) because the returned JSON is invalid, and the library states that the server returned a 400 error code. This isn't as helpful as it could be; the server returned an error message too, but with invalid JSON. If the server is fixed then this error will go away, but it may also be useful to improve that error message by including `cloudResponse.content` in it so that the developer has some idea what the server did return, even if it's invalid JSON.

**Comment by Steve51D** [comment]
Thanks @stuartlangridge,

The issue with invalid characters in the response has been resolved for the next release of our cloud service, which is scheduled to be in just over a week.

I've added the cloud request engine error message enhancement to the development backlog. Will update this issue again once one or both of these changes are available publicly.

**Comment by Steve51D** [comment]
The error message enhancement will be available in 4.0.4

**Comment by stuartlangridge** [comment]
Unless I'm missing something, the server response isn't fixed:

```bash
$ curl https://cloud.51degrees.com/api/v4/accessibleProperties?resource=ABC%0A
{ "status":"400", "errors": ["'ABC
' is not a valid resource key."] }
```

**Comment by jwrosewell** [comment]
@ben51degrees to verify and advise.

**Comment by ben51degrees** [comment]
Hi @stuartlangridge ,
You're correct. The fix actually only considered the environment newline, which is the Windows format `\r\n`. I've made the change to consider all forms of newline, so I will come back and close this once that is released to production.

**Comment by ben51degrees** [comment]
Hi @stuartlangridge ,
Closing this in favour of [cloud issue  #2](https://github.com/51Degrees/cloud-issues/issues/2).
The error message has been addressed in this python code, so the remaining issue lies with the cloud service.

Thanks,
Ben
